server:
  port: 8061
   
spring: 
  application:
    name: conversion-factor
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/
        - id: test_route
          uri: http://baeldung.com
          predicates:
            - Path=/test/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  
