server:
  port: 8061
   
spring: 
  application:
    name: conversion-factor


management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  
